services:

  # Wordpress Service
  wordpress:
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      wordpress_network:
        ipv4_address: 192.168.1.2
    depends_on:
      - db
    secrets:
      - wordpress_db_password

  #Db Service
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      wordpress_network:
        ipv4_address: 192.168.1.3
    secrets:
      - mysql_root_password
      - mysql_password

networks:
  wordpress_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

volumes:
  db_data:

secrets:
  wordpress_db_password:
    file: ./secrets/wordpress_db_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt
